[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path  = 'cache_forge'
optimizer = true
deny_warnings = true
solc-version = "0.8.21"


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
bsc-testnet = "${BSC_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

